# @package agent.coding

name: Coding
metadata:
  description: This node acts as a coding agent, generating Python code
    based on given subtask and relevant document or/and code snippet

script_folder: assets/blender_script/
anchor_script_file: assets/blender_script/anchor_coding.py
check_error_file: assets/blender_script/check_error.py
save_scripts: True
fix_error_attempts: 10

input_schema:
  type: state
  name: coding
output_schema:
  type: structured_output
  name: coding
tool_schemas: [ ]

edges:
  in_coming: [ ]
  out_going: [ ]

template_file: templates/prompt/coding.yaml

use_model: True

model_name: gpt-4o-mini
model_provider: ~
#model_api_key: <API-KEY>
output_schema_as_tool: True
chat_model: null