# @package agent.coding

name: Coding
use_model: True
metadata:
  description: This node acts as a coding agent, generating Python code
    based on given subtask and relevant document or/and code snippet

anchor_folder: assets/blender_script/

input_schema:
  type: state
  name: coding

output_schema:
  type: structured_output
  name: coding
edges:
  in_coming:
    - retriever
  out_going:
    - retriever
    - critic

tool_schemas: [ ]

model_name: gpt-4o
model_provider: openai
#model_api_key: <API-KEY>
output_schema_as_tool: True
chat_model: null