# @package agent.planner

name: Planner
metadata:
  description: This node acts as an planner agent, helps to break given task into smaller subtasks

max_subtasks: 5

input_schema:
  type: state
  name: planner
output_schema:
  type: structured_output
  name: planner
tool_schemas: [ ]

edges:
  in_coming:
    - start
  out_going: [ ]

template_file: templates/prompt/planner.yaml

use_model: True

model_name: qwen/qwen3-coder
model_provider: ~
#model_api_key: <API-KEY>
output_schema_as_tool: True
chat_model: null