# @package agent.planner

name: Planner
metadata:
  description: This node acts as an planner agent, helps to break given task into smaller subtasks

template_file: templates/prompt/general/planner.yaml

max_subtasks: 1

input_schema:
  type: state
  name: planner
chat_output:
  type: chat_output
  name: planner

edges:
  in_coming:
    - start
  out_going: []

use_model: True

model_name: x-ai/grok-4.1-fast #openai/gpt-4.0-mini
model_provider: ~
#model_api_key: <API-KEY>
output_schema_as_tool: True
chat_model: null