# @package agent.planner

name: Planner
use_model: True
metadata:
  description: This node acts as an planner agent, helps to break given task into smaller subtasks
input_schema:
  type: state
  name: planner
output_schema:
  type: structured_output
  name: planner
edges:
  in_coming:
    - start
  out_going:
    - retriever

tool_schemas: [ ]


model_name: gpt-4o-mini
model_provider: openai
#model_api_key: <API-KEY>
output_schema_as_tool: True
chat_model: null