# @package agent.retriever

name: Retriever
metadata:
  description: This node acts as a retriever agent, helps to retrieve relevant documents with given query from pre-defined vectorstore

db_path: vectorstores/faiss/
embedding_name: all-MiniLM-L6-v2.gguf2.f16.gguf

n_docs: 1

template_file: templates/prompt/retriever.yaml

input_schema:
  type: state
  name: retriever
output_schema:
  type: structured_output
  name: retriever
tool_schemas: [ ]

edges:
  in_coming: [ ]
  out_going: [ ]

use_model: True

model_name: minimax/minimax-m2:free
model_provider: ~
#model_api_key: <API-KEY>
output_schema_as_tool: True
chat_model: null