# @package agent.verification

name: Verification
metadata:
  description: This node acts as a verification agent, verifies whether
    fixes provided by critic agent are successfully solved and suggest solutions if not

save_rendered_dir: assets/rendered_images/verification
anchor_script_path: assets/blender_script/anchor_verification.py
refined_script_path: assets/blender_script/refined_version.py

verification_attempts: 1

input_schema:
  type: state
  name: verification
output_schema:
  type: structured_output
  name: verification
tool_schemas: [ ]

edges:
  in_coming: [ ]
  out_going:
    - end

template_file: templates/prompt/verification.yaml

use_model: True

model_name: gpt-4o-mini
model_provider: openai
#model_api_key: <API-KEY>
output_schema_as_tool: True
chat_model: null