#
#  Copyright (c) 2025
#  Minh NGUYEN <vnguyen9@lakeheadu.ca>
#
"""The module containing agent classes, with command and different capabilities"""
from __future__ import annotations

import logging
from typing import Union, Generic, Sequence, Any, Optional, TYPE_CHECKING
from typing_extensions import override, deprecated

from langchain_core.messages import ToolMessage, AIMessage, BaseMessage, HumanMessage
from langchain_core.prompt_values import PromptValue
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnableConfig
from langchain_core.tools.base import ToolCall

from src.registry import RegisterAgent, load_tool
from src.types import OutputT, ToolSchema
from src.base.chat import BaseChatAssistance
from src.utils.decorator import add_note_docstring

logger = logging.getLogger(__name__)


# @RegisterAgent(module_path=__name__, name='base_agent')
class BaseAgent(BaseChatAssistance, Generic[OutputT, ToolSchema]):
    """The Base Agent class using single system prompt and human template and being able to execute tools.\n
    However, just execute tools one once (no persistence)"""

    use_model: bool = None
    """Whether the agent uses model as brain. In other words, agent does not use LLM"""

    metadata: dict[str, str]
    """Metadata to describe the agent"""

    tool_schemas: list[Union[dict, ToolSchema]] | ToolSchema
    """Tool schema equipped to LLM (chat model). Just the arguments schema not executing function"""

    def __init_subclass__(cls):
        # super().__init_subclass__()
        ...

    # def __init__(
    #     self,
    #     *args,
    #     tool_schemas: ToolSchema | list[Union[ToolSchema, dict]] = None,
    #     **kwargs,
    # ):
    #     self.tool_schemas = tool_schemas
    #     super().__init__(**kwargs)

    def _convert_to_seq_message(self, input: Union[str, PromptValue]):
        if isinstance(input, str):
            return [HumanMessage(content=input)]
        elif isinstance(input, PromptValue):
            return input.to_messages()

        return input

    def loop_invoke(
        self,
        input: Union[str, PromptValue, Sequence[BaseMessage]],
        config: Optional[RunnableConfig] = None,
        *,
        stop: Optional[list[str]] = None
    ):

        ai_message = self.invoke(input, config, stop=stop)
        tool_calls = ai_message.tool_calls

        messages = [*self._convert_to_seq_message(input), ai_message]

        if tool_calls:
            for tool_call in tool_calls:
                tool_message = self.create_tool_message(
                    content=self._execute_tool(tool_call),
                    _id=tool_call['id']
                )
                messages.append(tool_message)

        return messages

    def _execute_tool(self, tool_call: Union[ToolCall, dict]):
        tool = load_tool(tool_call['name'])

        return tool.invoke(input=tool_call['args'])

    @add_note_docstring("This function is now used for only 'COMP-5112 project', don't call outside")
    def chat_model_call(self, formatted_prompt: PromptValue, *args, **kwargs) -> OutputT:
        """This method actually calls chat model and response follow ``output_schema``"""

        # get an original ai message generated by chat model
        ai_message = self.invoke(formatted_prompt)
        # get tool calls
        response = self._parse_output(ai_message)

        # conversation of this call
        messages = [*formatted_prompt.to_messages(), ai_message]

        return response, messages

    # @deprecated("Use `_get_tool_calls` instead")
    def _parse_output(self, ai_message: AIMessage) -> Any:
        """Parse the structured output in raw ai message in ``tool_calls``

        Get only the last shema in ``tool_calls``
        """

        try:
            dict_output = ai_message.tool_calls[-1]['args']
            # expect structure has only the first field
            key = list(dict_output.keys())[0]
            return dict_output[key]

        except (IndexError, ValueError, KeyError):
            # try to parse when the content may be ```json\n{}\n```
            return self._parse_json_content(ai_message.content)

    def _parse_json_content(self, text: str):
        """Parse the structured output from text content"""

        import json, re

        text = text.strip()
        if text.startswith("```"):
            text = re.sub(r"^```[a-zA-Z]*", "", text).strip("` \n")
        match = re.search(r"\{.*\}", text, re.DOTALL)

        if match:
            try:
                return json.loads(match.group())
            except ValueError:
                pass

        return text

    @override
    def _validate_schemas(self):
        """Initialize schemas including model output (from chat) + tool schemas (from agent)"""

        self.tool_schemas = self._convert_to_list(seq=self.tool_schemas)
        self.output_schema = self._convert_to_list(seq=self.output_schema)

        schemas = self.tool_schemas + self.output_schema
        schemas = [
            self.fetch_schema(tool_schema)
            for tool_schema in schemas
        ]

        return schemas

    @override
    def _prepare_message_templates(self, *args, **kwargs):
        super()._prepare_message_templates(*args, **kwargs)

    @override
    def _prepare_chat_template(self, system_template=None, human_template=None) -> ChatPromptTemplate:
        return super()._prepare_chat_template(
            system_template=system_template,
            human_template=human_template
        )

    @deprecated("No longer needed")
    def anchor_call(self, *args, **kwargs):
        """Use this function to generate virtual data that match output schema in reality.
        The main purpose is just test workflow but not call chat model really
        """
        ...

    @classmethod
    def create_tool_message(cls, content, _id):
        return ToolMessage(content=content, tool_call_id=_id)
